name: background_remover_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0



dependencies:
  flutter:
    sdk: flutter



  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  slider_button: ^2.1.0
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  build: ^2.4.2

  path_provider: ^2.1.2
  path: ^1.9.0
  carousel_slider: ^5.1.1
  auto_route: ^10.1.0+1
  dio: ^5.8.0+1
  hydrated_bloc: ^10.1.1
  tuple: ^2.0.2
  shimmer: ^3.0.0
  mocktail: ^1.0.4
  permission_handler: ^12.0.1
  device_info_plus: ^11.5.0
  image_picker: ^1.1.2
  gal: ^2.3.2
  image_background_remover: ^1.0.0
#  image_gallery_saver: ^2.0.3
  photo_manager: ^3.7.1
  image_cropper: ^9.1.0
  lottie: ^3.3.1
#  gallery_saver_plus: ^3.2.9
  crop_your_image: ^2.0.0



#
  supabase_flutter: ^2.9.1
#





  icon_builder:
    path: icon_builder







dependency_overrides:
  vibration: ^3.1.3



dev_dependencies:
  flutter_test:
    sdk: flutter




  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  flutter_lints: ^5.0.0
  auto_route_generator: ^10.0.1
  bloc_test: ^10.0.0







flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/lottie/





targets:
  $default:
    builders:
      icon_builder|icon_builder:
        generate_for:
          - lib/generated/icons_placeholder.dart


builders:
  icon_builder:
    import: "package:background_remover_app/icons_placeholder.dart"

